using SkiaSharp;

namespace UnoGallery.LiveTiles;

/// <summary>
/// Kaleidoscopic mandala. A "source" wedge contains an evolving line drawing
/// (slowly-rotating petals + orbiting nodes); the canvas is rotated N times
/// to draw the same wedge at each angle, plus mirrored for true reflective
/// symmetry. The result has perfect N-fold rotational and mirror symmetry,
/// like a kaleidoscope view, even though only one wedge is actually generated.
/// </summary>
public sealed class MandalaTile : ILiveTile
{
    const int Symmetry = 8;        // 8-fold rotational symmetry × mirror = 16 total wedges

    public string Caption => "Mandala";

    public ImmutableArray<SKColor> Palette { get; } = ImmutableArray.Create(
        new SKColor(8, 4, 22),
        new SKColor(120, 90, 220),
        new SKColor(255, 130, 220),
        new SKColor(255, 230, 150));

    public void Draw(SKCanvas canvas, SKRect dest, float t)
    {
        using var bg = new SKPaint { Color = Palette[0] };
        canvas.DrawRect(dest, bg);

        canvas.Save();
        canvas.ClipRect(dest);
        canvas.Translate(dest.MidX, dest.MidY);

        float r = MathF.Min(dest.Width, dest.Height) * 0.46f;
        float wedgeAngleDeg = 360f / Symmetry;

        // Record the source wedge ONCE per frame, then replay it 16 times via
        // rotation matrices. DrawPicture is a single Skia call regardless of
        // how many primitives the picture contains; the previous version paid
        // for ~100 ops × 16 wedges.
        using var recorder = new SKPictureRecorder();
        var rc = recorder.BeginRecording(new SKRect(-r, -r, r, r));
        DrawSourceWedge(rc, r, t);
        using var wedge = recorder.EndRecording();

        for (int slice = 0; slice < Symmetry; slice++)
        {
            float angleDeg = slice * wedgeAngleDeg;
            var rot = SKMatrix.CreateRotationDegrees(angleDeg);
            canvas.DrawPicture(wedge, in rot);

            var mirror = SKMatrix.CreateScale(-1f, 1f);
            var rotMirror = SKMatrix.Concat(rot, mirror);
            canvas.DrawPicture(wedge, in rotMirror);
        }

        // Centre cap covers the seam where wedges meet.
        using var cap = new SKPaint
        {
            IsAntialias = true,
            Shader = SKShader.CreateRadialGradient(
                new SKPoint(0, 0), r * 0.18f,
                new[] { Palette[3].WithAlpha(230), Palette[2].WithAlpha(60), new SKColor(0, 0, 0, 0) },
                new[] { 0f, 0.55f, 1f },
                SKShaderTileMode.Clamp),
        };
        canvas.DrawCircle(0, 0, r * 0.18f, cap);

        canvas.Restore();
    }

    /// <summary>
    /// Paint into a single wedge — the slice between angle 0 and 2π/Symmetry.
    /// The rest of the mandala is generated by rotating and mirroring this
    /// content. Each frame the source motifs evolve so the symmetric pattern
    /// is never static.
    /// </summary>
    void DrawSourceWedge(SKCanvas canvas, float r, float t)
    {
        // 1. Petal arcs — a few curves swept along the wedge, drifting with time.
        for (int i = 0; i < 4; i++)
        {
            float arcR = r * (0.30f + i * 0.18f);
            float drift = MathF.Sin(t * 0.4f + i * 0.7f) * 0.10f;

            using var paint = new SKPaint
            {
                Color = LerpPalette(i / 4f).WithAlpha(190),
                Style = SKPaintStyle.Stroke,
                StrokeWidth = MathF.Max(1f, r * 0.012f),
                IsAntialias = true,
                StrokeCap = SKStrokeCap.Round,
            };
            using var path = new SKPath();
            int seg = 24;
            for (int s = 0; s <= seg; s++)
            {
                float a = (s / (float)seg) * (MathF.Tau / Symmetry);
                float modR = arcR + MathF.Sin(a * 6f + t * 1.3f + i) * r * 0.025f + drift * r;
                float px = MathF.Cos(a) * modR;
                float py = MathF.Sin(a) * modR;
                if (s == 0) path.MoveTo(px, py);
                else path.LineTo(px, py);
            }
            canvas.DrawPath(path, paint);
        }

        // 2. Orbiting node along the wedge — small disc with a glow halo.
        float orbitR = r * (0.55f + 0.30f * MathF.Sin(t * 0.7f));
        float orbitA = (0.10f + 0.80f * (0.5f + 0.5f * MathF.Sin(t * 0.5f))) * (MathF.Tau / Symmetry);
        float nx = MathF.Cos(orbitA) * orbitR;
        float ny = MathF.Sin(orbitA) * orbitR;
        using (var halo = new SKPaint
        {
            IsAntialias = true,
            Shader = SKShader.CreateRadialGradient(
                new SKPoint(nx, ny), r * 0.10f,
                new[] { Palette[3].WithAlpha(220), new SKColor(0, 0, 0, 0) },
                SKShaderTileMode.Clamp),
        })
        {
            canvas.DrawCircle(nx, ny, r * 0.10f, halo);
        }
        using (var dot = new SKPaint { IsAntialias = true, Color = Palette[3] })
        {
            canvas.DrawCircle(nx, ny, r * 0.025f, dot);
        }

        // 3. Radial spokes from centre — count drifts so the structure breathes.
        int spokes = 3;
        for (int s = 0; s < spokes; s++)
        {
            float a = (s + 1) / (float)(spokes + 1) * (MathF.Tau / Symmetry);
            float len = r * (0.75f + 0.10f * MathF.Sin(t * 0.8f + s));
            using var spokePaint = new SKPaint
            {
                Color = Palette[1].WithAlpha(160),
                Style = SKPaintStyle.Stroke,
                StrokeWidth = MathF.Max(1f, r * 0.008f),
                IsAntialias = true,
                StrokeCap = SKStrokeCap.Round,
            };
            canvas.DrawLine(0, 0, MathF.Cos(a) * len, MathF.Sin(a) * len, spokePaint);
        }
    }

    SKColor LerpPalette(float t)
    {
        t = Math.Clamp(t, 0f, 0.999f);
        float scaled = t * (Palette.Length - 1);
        int idx = (int)scaled;
        float f = scaled - idx;
        var a = Palette[idx];
        var b = Palette[Math.Min(idx + 1, Palette.Length - 1)];
        return new SKColor(
            (byte)(a.Red + (b.Red - a.Red) * f),
            (byte)(a.Green + (b.Green - a.Green) * f),
            (byte)(a.Blue + (b.Blue - a.Blue) * f));
    }
}
